### ISSUE TITLE
Log  nydusd's stderr and stdout to nydus-snapshotter  log

### ISSUE THREAD

**Issue by zyfjeff** [containerd/nydus-snapshotter#104]
At present, the log of nydusd is not output to the log file. When panic occurs in Nydusd, the information of the panic will be lost. Therefore, it is necessary to output stdout and stderr to the log file as well.

```
	args = append(args, "--apisock", d.GetAPISock())
	args = append(args, "--log-level", d.LogLevel)
	if !d.LogToStdout {
		args = append(args, "--log-file", d.LogFile())
	}

	log.L.Infof("start nydus daemon: %s %s", m.nydusdBinaryPath, strings.Join(args, " "))

	cmd := exec.Command(m.nydusdBinaryPath, args...)
	if d.LogToStdout {
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stdout
	}
	return cmd, nil
```

**Comment by changweige** [comment]
Are you working on this issue? Can we try this crate https://docs.rs/log-panics/latest/log_panics/?
Or pipe nydusd stderr to snapshotter log files?

**Comment by jiangliu** [comment]
> Are you working on this issue? Can we try this crate https://docs.rs/log-panics/latest/log_panics/? Or pipe nydusd stderr to snapshotter log files?

We need minimize dependency as much as possible. We have faced serious issue when packaging nydus for debian due to dependency.
