### ISSUE TITLE
Snapshotter won't remove blobcache after restarting responding to nerdctl image rm

### ISSUE THREAD

**Issue by changweige** [containerd/nydus-snapshotter#107]
When a container image is not used or referenced by a container, nydus-snapshotter is responsible to do GC for the blobcache files. But restarting snapshotter ends in states missing and no blobcache files GS is performed.

**Comment by imeoer** [comment]
Could you describe the reproduction steps in detail? thanks!

**Comment by jiangliu** [comment]
I can't reproduce this with the latest main branch too.

**Comment by changweige** [comment]
Yes. it is no longer reproduced. I am closing it.
