### ISSUE TITLE
Support shared domain for erofs + fscache daemon

### ISSUE THREAD

**Issue by userzj** [containerd/nydus-snapshotter#161]
Previously,  the commit `erofs: basic support for erofs + fscache daemon`  supported erofs with fscache daemon.    
Since the shared domain feature is not be implemented in Linux Kernel, the config field `DomainID` is unused.     
The cfg field "DomainID" is not used since the shared domain feature is not implemented in Linux Kernel.
After Kernel implements this feature, nydus-snapshotter should adapt the `DomainID` field.

**Comment by changweige** [comment]
Good to hear about it 👍

**Comment by hsiangkao** [comment]
Okay, let's keep open this issue until the patchset is landed upstream.

**Comment by hsiangkao** [comment]
https://github.com/containerd/nydus-snapshotter/pull/211
already merged.
