### ISSUE TITLE
nydus snapshotter should to get auth from docker auth config and fill in config template

### ISSUE THREAD

**Issue by zyfjeff** [containerd/nydus-snapshotter#230]
For private images, currently, our auth needs to be manually filled into the config template, this experience is very poor, and we need to support getting from the docker auth config to populate.

**Comment by imeoer** [comment]
Is this code https://github.com/containerd/nydus-snapshotter/blob/870ccffbc40e16abf7de63a117dfdacdde44f8b2/config/daemonconfig.go#L180 not work?

**Comment by zyfjeff** [comment]
my fault, I don't see this code.
