### ISSUE TITLE
automatically fill registry http scheme for daemon config

### ISSUE THREAD

**Issue by imeoer** [containerd/nydus-snapshotter#235]
We'd better fill `"scheme": "https"` field as default in the daemon config, but still can fallback to `"scheme": "http"` by pre-checking the registry server.

**Comment by changweige** [comment]
snapshotter would better not modify the configuration in silent provided by users

**Comment by imeoer** [comment]
users can still fill a preferred value.

**Comment by changweige** [comment]
If the user never provides HTTP policy configuration item in the nydusd config file, snapshotter can do as what you are proposing. But should do nothing if the field is ever filled.

**Comment by imeoer** [comment]
We can provide a recommended nydusd config with the empty scheme, snapshotter uses `https` as default, and can fallback to `http` by pre-checking the registry server, in the same time users can still fill a preferred value for performance consideration. Maybe we'd better support it in nydusd directly?

**Comment by changweige** [comment]
We can try it in nydusd. But I think it's better to override the user's behavior. Automacitiy is kind of this override

**Comment by imeoer** [comment]
https://github.com/dragonflyoss/image-service/issues/843
