### ISSUE TITLE
Don't show nydusd config file to other users on host

### ISSUE THREAD

**Issue by changweige** [containerd/nydus-snapshotter#246]
Nydusd stores registry auth in its json config file on host. We'd better not store or expose sensitive information on host.
Now the configuration file has permission bits of 0644 which means non-root user can read the file.
To reduce the exposure risk, we should not let non-root user read it.

**Comment by imeoer** [comment]
Better not to write the file to disk if possible.

**Comment by changweige** [comment]
Ture. Perhaps we can open a API from nydusd to pass AUTH
