### ISSUE TITLE
Create releases

### ISSUE THREAD

**Issue by liubin** [containerd/nydus-snapshotter#25]
Now users can download nydus-snapshotter from image-service, but nydus-snapshotter repo has not any release yet.

Related to https://github.com/kata-containers/tests/issues/4446

**Comment by changweige** [comment]
Nydus-snapshotter now has function of  automatic releasing when a tag pushed. I guess it should meet current requirement.

**Comment by changweige** [comment]
I just release v0.1.0 as the initial released version. Hope it will be helpful to you.

**Comment by liubin** [comment]
Thank you.
