### ISSUE TITLE
[bug] nydusd config info

### ISSUE THREAD

**Issue by Desiki-high** [containerd/nydus-snapshotter#271]
When use config for nydus-snapshotter like 
`
{
"access_pattern": true,
"latest_read_files": true
}
`
These two fields will not appear in the nydusd configuration of each image, but they are used by Nydus RafsConfig
![image](https://user-images.githubusercontent.com/59167816/205539895-dd2f99e0-6f37-41c8-a4e4-5656e2aa1366.png)
So the nydus-snapshotter just ignore these two fields in https://github.com/containerd/nydus-snapshotter/blob/main/config/daemonconfig/fuse.go
![image](https://user-images.githubusercontent.com/59167816/205540497-8cfb26f9-c332-4596-b0fe-468ca928ff6c.png)

In this case we can't use the metrics api like /api/v1/metrics/pattern /api/v1/metrics/files?latest_read_files=true

**Comment by changweige** [comment]
Yes. Nydus-snapshotter does not pass the parameters (`access_pattern` and `latest_read_files`) to nydusd. So the nydusd capability is not exposed yet. Welcome to raise a PR to enable to feature. 😁

**Comment by changweige** [comment]
Fixed by https://github.com/containerd/nydus-snapshotter/pull/272
