### ISSUE TITLE
use `findmnt` to judge `IsLikelyNotMountPoint`

### ISSUE THREAD

**Issue by luodw** [containerd/nydus-snapshotter#30]
When `nydusd` is down unexpectedly, `IsLikelyNotMountPoint` can not run expectedly, as stat fuse mountpoint will failed and the fuse mountpoint can not cleanup when image is removed. So I think [IsLikelyNotMountPoint](https://github.com/containerd/nydus-snapshotter/blob/main/pkg/utils/mount/mount_linux.go#L20) use command `findmnt` maybe more suitable. 

here can refer to [this](https://github.com/kubernetes-retired/kubedash/blob/master/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/mount/nsenter_mount.go#L130), 

```golang
func (m *Mounter) IsLikelyNotMountPoint(file string) (bool, error) {
	file, err := filepath.Abs(file)
	if err != nil {
		return true, err
	}
	cmdPath, err := exec.LookPath("findmnt")
	if err != nil {
		// no findmnt found, judge moutpoint by device
		log.L.Printf("no findmnt command found, use device to judge")
		return m.isLikelyNotMountPoint(file)
	}
	args := []string{"--types", "fuse", "-o", "target", "--noheadings", "--target", file}
	log.L.Printf("findmnt command: %v %v", cmdPath, args)

	out, err := exec.Command(cmdPath, args...).CombinedOutput()
	if err != nil {
		// if findmnt didn`t return, just claim it's not a mount point
		return true, err
	}
	strOut := strings.TrimSuffix(string(out), "\n")
	log.L.Printf("IsLikelyNotMountPoint findmnt output: %v", strOut)
	if strOut == file {
		return false, nil
	}

	return true, nil
}

func (m *Mounter) isLikelyNotMountPoint(file string) (bool, error) {
	stat, err := os.Stat(file)
	if err != nil {
		return true, err
	}
	rootStat, err := os.Stat(filepath.Dir(strings.TrimSuffix(file, "/")))
	if err != nil {
		return true, err
	}
	// If the directory has a different device as parent, then it is a mountpoint.
	if stat.Sys().(*syscall.Stat_t).Dev != rootStat.Sys().(*syscall.Stat_t).Dev {
		return false, nil
	}

	return true, nil
}
```

**Comment by bergwolf** [comment]
@luodw Thanks for the suggestion! While `findmnt` works, I think it is better **not** to add the extra dependency on other commands, in order to reduce nydus-snapshotter deployment and management complexity. If `isLikelyNotMountPoint` is not reliable enough, we can improve its logic to make it more reliable. wdyt?

**Comment by luodw** [comment]
@bergwolf yes, you are right, maybe we can refer to `findmnt` implementation.
