### ISSUE TITLE
broken --enable-metrics option in v0.5.0

### ISSUE THREAD

**Issue by imeoer** [containerd/nydus-snapshotter#315]
https://github.com/containerd/nydus-snapshotter/blob/main/misc/snapshotter/entrypoint.sh#L20

This option has been removed from v0.5.0, what's new should be given here?

**Comment by imeoer** [comment]
cc @sctb512

**Comment by imeoer** [comment]
We shouldn't make some incompatible changes between minor releases.

**Comment by sctb512** [comment]
> https://github.com/containerd/nydus-snapshotter/blob/main/misc/snapshotter/entrypoint.sh#L20
> 
> This option has been removed from v0.5.0, what's new should be given here?

Replaced it by `--metrics-address`. Reference  to containerd https://github.com/containerd/containerd/blob/badb66113cceb480b6c37fd18adae400f309c57c/docs/man/containerd-config.toml.5.md#format

Got it. We should reserve the `--enable-metrics` until next version.

**Comment by changweige** [comment]
In fact, `--enable-metrics` never  works properly. Specifically speaking, the exported metrics are wrongly converted and calculated and only a small number is exported. We mean to support nydusd lifecycle metrics and nydusd filesystem ops metrics officially from v0.5.0. If we still keep the parameter `--enable-metrics`, it is somewhat duplicated from newly added `metrics-address` which expose metrics to Prometheus scraper. Moreover, nydus-snapshotter never has a working endpoint to export those metrics. So I don't think any breaking change is introduced. Quite the opposite, it is fixed and works from now on.

**Comment by changweige** [comment]
> At least we shouldn't break the snapshotter startup (`Incorrect Usage. flag provided but not defined: -enable-metrics`), how about just giving a warning when the `--enable-metrics` is specified?

I guess the users shouldn't use `--enable-metrics` before. I agree we should fix the example snapshotter docker file here https://github.com/containerd/nydus-snapshotter/blob/main/misc/snapshotter/entrypoint.sh#L20 . What makes me strange is why k8s e2e test is passed even the snapshotter can't start due to the disappeared parameter.

**Comment by changweige** [comment]
@liubin Do you have any idea why the k8s e2e test can be passed? 😂

**Comment by liubin** [comment]
@changweige 
If the `args` property of the `container` object, the args will be used as the entrypoint's main command.
https://github.com/containerd/nydus-snapshotter/blob/7e6afdb8e8d2c5825d619d9a7c55044c1a51ab76/tests/e2e/k8s/snapshotter-kubeconf.yaml#L60-L69

**Comment by changweige** [comment]
will be fixed by #321

**Comment by changweige** [comment]
Close it as it was fixed
