### ISSUE TITLE
Upgrade CRI API package to stable version

### ISSUE THREAD

**Issue by changweige** [containerd/nydus-snapshotter#360]
The package `k8s.io/cri-api/pkg/apis/runtime` has reached a stable version, so we should try to use the stable package rather than the alpha version.  We have to wait until containerd 1.7 is released and stargz-snapshotter upgrades its dependency on containerd

**Comment by PKizzle** [comment]
When using kubernetes versions >= 1.26 the alpha CRI versions [are no longer supported](https://kubernetes.io/blog/2022/11/18/upcoming-changes-in-kubernetes-1-26/#cri-api-removal). I receive the following error message:
```
CRI v1 image API is not implemented for endpoint "unix:///run/containerd-nydus/containerd-nydus-grpc.sock
```

**Comment by changweige** [comment]
> Supporting the v1 CRI API is especially useful for kubernetes users. When using kubernetes versions >= 1.26 the alpha CRI API [is no longer supported](https://kubernetes.io/blog/2022/11/18/upcoming-changes-in-kubernetes-1-26/#cri-api-removal). I receive the following error message:
> 
> ```
> CRI v1 image API is not implemented for endpoint "unix:///run/containerd-nydus/containerd-nydus-grpc.sock"
> ```
> 
> The linked kubernetes support article however suggests that containerd 1.6 is already compatible with the v1 CRI API.

It is caused by that nydus-snapshotter depends on stargz-snapshotter 0.13.1 which depends on CRI image API v1alpha2. If we upgrade stargz-snapshotter to its 0.14.0 now, the containerd 1.7.0-beta2 will be introduced to nydus-snapshotter. But I am not sure if it is suitable to depend on containerd of beta version. So I am waiting for the release of containerd 1.7. 0. cc @AkihiroSuda @ktock 

Nydus-snapshotter will release v0.6.0 this week. I think we can upgrade stargz-snapshotter to 0.14.0 on main branch after v0.6.0 is released, which will allow us to switch to the stable CRI image API

**Comment by changweige** [comment]
> Supporting the v1 CRI API is especially useful for kubernetes users. When using kubernetes versions >= 1.26 the alpha CRI API [is no longer supported](https://kubernetes.io/blog/2022/11/18/upcoming-changes-in-kubernetes-1-26/#cri-api-removal). I receive the following error message:
> 
> ```
> CRI v1 image API is not implemented for endpoint "unix:///run/containerd-nydus/containerd-nydus-grpc.sock"
> ```
> 
> The linked kubernetes support article however suggests that containerd 1.6 is already compatible with the v1 CRI API.

Nydus-snapshotter has support Kubernetes stable CRI API v1 from v0.7.0
