### ISSUE TITLE
support different nydus configurations

### ISSUE THREAD

**Issue by liubogithub** [containerd/nydus-snapshotter#37]
Nydus supports several different types of storage backend, "localfs", "oss" and "registry".

Since users may use different backend for different images in order to meet different scenarios, it'd better to have nydus-snapshotter support multiple nydus configuration in one shot.

With that being said, how to choose a specific nydus config is not a straightforward thing as it depends on a container image's metadata.
Maybe we can leave an annotation in bootstrap.

**Comment by hsiangkao** [comment]
personally I don't like it since bootstrap is the part of container image format.
I don't think the backend configuration should be in the container image format.
It's a runtime decision.

**Comment by changweige** [comment]
Closed as no plan to implement it
