### ISSUE TITLE
Nydus logs lost in /var/lib/containerd-nydus/logs/

### ISSUE THREAD

**Issue by adamqqqplay** [containerd/nydus-snapshotter#442]
In the early version (v0.4.0) of [nydus snapshotter package](https://github.com/orgs/containerd/packages/container/package/nydus-snapshotter), the logs of nydusd are automatically output to the /var/lib/containerd-nydus/logs/ directory. So we can check the operation of nydusd according to the method in [this document](https://d7y.io/docs/setup/integration/nydus/#try-nydus-with-nerdctl).

`grep mirrors /var/lib/containerd-nydus/logs/**/*log`

![image](https://user-images.githubusercontent.com/29459113/229682422-f81077f0-9112-41a2-ba8d-b99a274a4f69.png)

But now these logs are not output by default, which makes it difficult to use in the container environment positioning problem.

Hope to be able to output the nydusd log to the original place by default when the nydus-snapshotter image is packaged.

**Comment by changweige** [comment]
Can you please print your nydusd command line like `ps -ef|grep nydusd`

**Comment by changweige** [comment]
It's because you enabled `--log-to-stdout` for nydus-snapshotter, which means both nydusd and nydus-snapshotter would print logs to stdout

**Comment by adamqqqplay** [comment]
> It's because you enabled `--log-to-stdout` for nydus-snapshotter, which means both nydusd and nydus-snapshotter would print logs to stdout

Thanks, maybe there is a bug in the helm chart or the snapshotter Dockerfile, I will try to fix it.

Another question is, when `--log-to-stdout` is not specified, will the log be automatically output to `/var/lib/containerd-nydus/logs/`?

**Comment by changweige** [comment]
> > It's because you enabled `--log-to-stdout` for nydus-snapshotter, which means both nydusd and nydus-snapshotter would print logs to stdout
> 
> Thanks, maybe there is a bug in the helm chart or the snapshotter Dockerfile, I will try to fix it.
> 
> Another question is, when `--log-to-stdout` is not specified, will the log be automatically output to `/var/lib/containerd-nydus/logs/`?

Yes. It's default to logs
