### ISSUE TITLE
install codecov for nydus-snapshotter repo

### ISSUE THREAD

**Issue by imeoer** [containerd/nydus-snapshotter#478]
@dmcgowan @estesp Would you help to install the codecov app for nydus-snapshotter repo. Thanks!

https://github.com/apps/codecov/installations/new

![image](https://github.com/containerd/nydus-snapshotter/assets/1524576/38971929-a967-410b-b76d-f05fe6637d93)

**Comment by changweige** [comment]
LGTM. Please help us if possible 😁

**Comment by dmcgowan** [comment]
Done
