### ISSUE TITLE
Support download blob layers to cache dir

### ISSUE THREAD

**Issue by zyfjeff** [containerd/nydus-snapshotter#48]
Our Nydusd supports the localfs mode to start, in other words, the blob layer is placed on the local file system in advance, but at present, we do not provide the auxiliary ability to put the blob layer in the corresponding directory, which requires us manually from the registry download the blob layer and extract it to the corresponding directory. Obviously, this is more complicated to operate and maintain. We can support this scenario through nydus-snapshotter, which downloads the blob layer from the registry through snapshotter and puts it into the blob cache directory configured by Nydusd.

**Comment by imeoer** [comment]
When should we download the blob in advance and what if the container is started before all blobs are downloaded?

**Comment by zyfjeff** [comment]
@imeoer Like the OCI image pull process, the blob layer will be downloaded when the image is pulled

**Comment by imeoer** [comment]
This seems to defeat the purpose of on-demand load, why do we still need to use nydus after all layers are pulled?

**Comment by zyfjeff** [comment]
@imeoer For example, in the scenario of image preloading, the user doesn't want to use on-demand loading, but load the image in advance. At this time, it can be preloading through snapshotter. Instead of manually downloading in advance through other hack way, the standard mirror pull process is followed.
