### ISSUE TITLE
Support nydusd fuse threads config

### ISSUE THREAD

**Issue by Desiki-high** [containerd/nydus-snapshotter#492]
Nydusd default ```fuse-threads``` is 4, but it is not suitable for all images and machines. So does it make sense to add it to the configuration file?

**Comment by changweige** [comment]
The snapshotter's TOML configuration file is capable of customizing the threads number for nydusd now. https://github.com/containerd/nydus-snapshotter/blob/88ccb5207ff5c637685fa798bba1ef5bd841877b/misc/snapshotter/config.toml#LL34C1-L34C1
