### ISSUE TITLE
The blobs annotation in manifest should be deprecated

### ISSUE THREAD

**Issue by imeoer** [containerd/nydus-snapshotter#5]
Currently, nydus image puts an annotation to the manifest to track all referenced blobs in bootstrap: [nydus](https://github.com/dragonflyoss/image-service/blob/7f3efa78ae3af27fbc4a0c7364672d0005ae8f56/contrib/nydusify/examples/manifest/manifest.json#L38)

This will cause the label kv size limitation to be exceeded in containerd when acceld/buildkit write a nydus manifest included a large number of blobs into the content store: [containerd](https://github.com/containerd/containerd/blob/62a4e7020ddb9863980aa9eec5f1e0c4f97b779c/labels/validate.go#L30)

I noticed that the blobs annotation only be used for blob cache gc in nydus-snapshotter: [nydus-snapshotter](https://github.com/containerd/nydus-snapshotter/blob/672434e7b31924f286932de4ea1941f66fb03b59/pkg/filesystem/nydus/fs.go#L428)

A feasible workaround is to use nydusd sock API to get the blobs in use, instead of using the list in manifest annotation, so we can remove the annotation from acceld/buildkit.

**Comment by liubogithub** [comment]
Is this fixed or not?

**Comment by jiangliu** [comment]
When containerd issues `PREPARE` command to the snapshotter, it carries information about the parent layer id.
It's possible to track all data blobs referenced by a nydus image/meta blob.

**Comment by changweige** [comment]
The PR https://github.com/containerd/nydus-snapshotter/pull/233 is fixing this.
Nydusify has already dropped the label when converting images. The only purpose of having the label is for blob cache GC.
But contained also has a GC mechanism and a single snapshot is shared between images, which means contained won't remove a snapshot if it is still referenced by another container image. So the PR safely kicks out snapshotter cache GC code and just removes the blob cache if it corresponds to a committed layer/snapshot.

In addition, it removes the label from nydus-snapshotter

**Comment by changweige** [comment]
Solved. The blobs list is dropped from nydus image
