### ISSUE TITLE
Provide CRI like configuration for registry access

### ISSUE THREAD

**Issue by imeoer** [containerd/nydus-snapshotter#51]
Currently the downloading of layers (including the bootstrap layer) is done entirely by snapshotter, not containerd, so we need to consider these:

1. registry mirror support;
2. choose http/https registry scheme;
3. client https tls cert support;
4. retryable http request; 
5. registry auth for multiple registries;
6. retryable multiple mirrors;

Maybe we can support the CRI like configuration like this:

![image](https://user-images.githubusercontent.com/1524576/169488312-ef9a46d6-0dbe-4042-bcdd-498089d6ccb2.png)

**Comment by changweige** [comment]
Looks like this style is already deprecated. https://github.com/containerd/containerd/blob/main/docs/cri/registry.md

We should move to https://github.com/containerd/containerd/blob/main/docs/cri/config.md#registry-configuration fashion

**Comment by changweige** [comment]
> Currently the downloading of layers (including the bootstrap layer) is done entirely by snapshotter, not containerd, so we need to consider these:

By which configuration or use case, data layers, or bootstrap is downloaded by snapshotter? Or do you mean nydusd?

**Comment by changweige** [comment]
Should this be marked as done @imeoer ?

**Comment by imeoer** [comment]
@changweige It's still in progress.
