### ISSUE TITLE
Support to pass the image name to the remote mount slice

### ISSUE THREAD

**Issue by ChengyuZhu6** [containerd/nydus-snapshotter#516]

**Comment by imeoer** [comment]
Please describe the details and use case.

**Comment by ChengyuZhu6** [comment]
In the scenario of a confidential container, the image needs to be downloaded inside the vm, so an external method is needed to pass the name of the image to the vm. Therefore, the snapshotter needs to transfer the image name information through the mount slice.

**Comment by imeoer** [comment]
> In the scenario of a confidential containers, the image needs to be downloaded inside the vm, so an external method is needed to pass the name of the image to the vm. Therefore, the snapshotter needs to transfer the image name information through the mount slice.

How can we let VM know the registry auth and mirror info?

**Comment by ChengyuZhu6** [comment]
> > In the scenario of a confidential containers, the image needs to be downloaded inside the vm, so an external method is needed to pass the name of the image to the vm. Therefore, the snapshotter needs to transfer the image name information through the mount slice.
> 
> How can we let VM know the registry auth and mirror info?

The auth information will be passed in the vm through a plugin with a confidential channel.

**Comment by jiangliu** [comment]
Fixed
