### ISSUE TITLE
Snapshot of writable layer

### ISSUE THREAD

**Issue by aledbf** [containerd/nydus-snapshotter#532]
👋 Hi, is it possible to create a snapshot of the writable layer and push it to the registry?
Thanks!

**Comment by imeoer** [comment]
Hi, did you mean it's like `docker commit` for saving the container as a new nydus image? We are planning to create a `nydusify commit` command for this.

**Comment by aledbf** [comment]
> Hi, did you mean it's like docker commit for saving the container as a new nydus image?

Yes, exactly that.

Glad to hear this is already planned
Thanks!

**Comment by imeoer** [comment]
@aledbf reopened it, will sync the status once we are ready. :)

**Comment by aledbf** [comment]
@imeoer friendly ping. Any update?
Thanks!

**Comment by imeoer** [comment]
> @imeoer friendly ping. Any update? Thanks!

cc @PerseidMeteor

**Comment by aledbf** [comment]
@imeoer friendly ping. Any update?
Thanks!

**Comment by imeoer** [comment]
Hi @aledbf , here is the `nydusify commit` subcommand: https://github.com/dragonflyoss/nydus/blob/master/docs/nydusify.md#commit-nydus-image-from-containers-changes
