### ISSUE TITLE
release: Provide s390x and arm64 released tarballs

### ISSUE THREAD

**Issue by fidencio** [containerd/nydus-snapshotter#548]
Confidential Containers is now depending on the nydus-snapshotter, and having an official release for the architecures we support (amd64, which is already there; and s390x) and will support in the future (arm64) would be amazing!

**Comment by imeoer** [comment]
Have you time to take a look? @sctb512 @changweige

**Comment by sctb512** [comment]
> Have you time to take a look? @sctb512 @changweige

Yes, it is necessary to release multi-architecture packages. I will look into it soon.

**Comment by sctb512** [comment]
The binaries we released are now statically linked.
```shell
$ wget https://github.com/containerd/nydus-snapshotter/releases/download/v0.13.3/nydus-snapshotter-v0.13.3-x86_64.tgz
$ tar -zxvf nydus-snapshotter-v0.13.3-x86_64.tgz
$ ldd nydus-snapshotter/*
nydus-snapshotter/containerd-nydus-grpc:
	not a dynamic executable
nydus-snapshotter/nydus-overlayfs:
	not a dynamic executable
nydus-snapshotter/optimizer-nri-plugin:
	not a dynamic executable
nydus-snapshotter/optimizer-server:
	statically linked
```

So, I believe it can run on different architectures now.

**Comment by sctb512** [comment]
Additionally, we can release packages for different architectures as well.  See https://github.com/containerd/containerd/releases/tag/v1.7.7

**Comment by sctb512** [comment]
Related to https://github.com/containerd/nydus-snapshotter/pull/418
