### ISSUE TITLE
Multi-arch support for a nydus-snapshotter image

### ISSUE THREAD

**Issue by BbolroC** [containerd/nydus-snapshotter#583]
The project is currently utilized by `confidential-containers`. Presently, the CI system is set up exclusively for x86_64 architecture. As the project progresses, there's a need to expand the CI to include support for other platforms. However, the deployment relies on an image, `ghcr.io/containerd/nydus-snapshotter`, which is only compatible with x86_64 architecture. It would be advantageous to transform this into a multi-arch image using a GitHub Actions workflow.

**Comment by imeoer** [comment]
@BbolroC :( It seems have a wrap line problem when handle latest and tag:

https://github.com/containerd/nydus-snapshotter/actions/runs/8325473739/job/22779362791

![image](https://github.com/containerd/nydus-snapshotter/assets/1524576/438f03bc-e405-4527-a364-dbecfb7733c1)

**Comment by BbolroC** [comment]
@imeoer Thanks for sharing the log. I missed a tagging part. I will update the PR. 😉
