### ISSUE TITLE
Clarify status of eStargz support

### ISSUE THREAD

**Issue by aochagavia** [containerd/nydus-snapshotter#587]
The [readme file](https://github.com/containerd/nydus-snapshotter) for nydus-snapshotter mentions that it supports eStargz out-of-the-box. However, in the [example config](https://github.com/containerd/nydus-snapshotter/blob/c7841c765b90058895c658355f4e9a19c8989625/misc/snapshotter/config.toml) I see an experimental option called enable_stargz. Does that mean that eStargz support is experimental? I think it would be useful to clarify this somewhere (and I'd love to know the answer myself).

**Comment by imeoer** [comment]
Sorry for the confusion, supporting estargz is still experimental and in fact the current implementation is not efficient enough, we will fix the doc to update the statement, thanks!
